export interface SurveyData extends Record<string, string> {
  'Timestamp': string;
  'What is your name?': string;
  // 'I understand something better after I': string;
  // 'During online classes, I understood something better after I': string;
  // 'I would rather be considered': string;
  // 'While learning through online mode, I would rather be considered': string;
  // 'When I think about what I did yesterday, I am most likely to get': string;
  // 'When I used to think about what I had done a day before, I was most likely to get': string;
  // 'I tend to': string;
  // 'During online learning, I would tend to': string;
  // 'When I am learning something new, it helps me to': string;
  // 'During online classes when I was learning something new, it would help me to': string;
  // 'If I were a teacher, I would rather teach a course': string;
  // 'If I were a teacher teaching in online mode, I would rather teach a course': string;
  // 'I prefer to get new information in': string;
  // 'While learning online, I preferred to get new information in': string;
  // 'Once I understand': string;
  // 'During online learning, once I understood': string;
  // 'In a study group while working on difficult material, I am more likely to': string;
  // 'In a breakout room while working on difficult material, I was more likely to': string;
  // 'I find it easier': string;
  // 'During online classes, I found it easier': string;
  // 'In a book with lots of pictures and charts, I am likely to': string;
  // 'While studying a book with lots of pictures and charts by myself during COVID, I was likely to': string;
  // 'When I solve maths problems': string;
  // 'During online classes, when I solved maths problems': string;
  // 'In classes I have taken,': string;
  // 'In online classes I have taken,': string;
  // 'In reading non-fiction, I prefer': string;
  // 'During online mode, while reading non-fiction, I preferred': string;
  // 'I like teachers': string;
  // 'During online classes, I liked teachers': string;
  // "When I'm analysing a story or a novel": string;
  // "While learning in online mode, when I'm analysing a story or a novel": string;
  // 'When I start a homework problem, I am more likely to': string;
  // 'During online mode, when I started a homework problem, I was more likely to': string;
  // 'I prefer the idea of': string;
  // 'During online classes, I preferred the idea of': string;
  // 'I remember best': string;
  // 'While learning in online mode, I remembered best': string;
  // 'It is more important to me that an instructor': string;
  // 'In online classes, it was more important to me that an instructor': string;
  // 'I prefer to study': string;
  // 'During online classes, I preferred to study': string;
  // 'I am more likely to be considered': string;
  // 'While learning in online mode, I was more likely to be considered': string;
  // 'When I get directions to a new place, I prefer': string;
  // 'When I get directions to a new place, I tend to prefer': string;
  // 'I learn': string;
  // 'In online learning mode, I learnt': string;
  // 'I would rather first': string;
  // 'During online classes, I would rather first': string;
  // 'When I am reading for enjoyment, I would like writers to': string;
  // 'During online learning, when I would read for enjoyment, I would like writers to': string;
  // 'When I see a diagram or sketch, I am most likely to remember': string;
  // 'When I saw a diagram or sketch in an online class, I was most likely to remember': string;
  // 'When considering a body of information, I am more likely to': string;
  // 'When considering a body of information in online learning mode, I was more likely to': string;
  // 'I more easily remember': string;
  // 'During online mode, I would more easily remember': string;
  // 'When I had to perform a task, I prefer to': string;
  // 'When I had to perform a task during an online class, I preferred to': string;
  // 'When someone is showing me data, I prefer': string;
  // 'During online mode, when someone showed me data, I preferred': string;
  // 'When writing a paper, I am more likely to': string;
  // 'When writing a paper during online classes, I was more likely to': string;
  // 'When I have to work on a group project, I first want to': string;
  // 'During online mode, when I had to work on a group project, I would first want to': string;
  // 'I consider it higher praise to call someone': string;
  // 'While learning in online mode, I would consider it higher praise to call someone': string;
  // 'When I meet people at a party, I am more likely to remember': string;
  // 'When I met people on Zoom during online classes, I was more likely to remember': string;
  // 'When I am learning a new subject, I prefer to': string;
  // 'When I was learning a new subject online, I preferred to': string;
  // 'During online learning mode, I was more likely to be considered': string;
  // 'I prefer courses that emphasise': string;
  // 'In online mode, I preferred courses that emphasise': string;
  // 'For entertainment, I would rather': string;
  // 'During COVID lockdown, for entertainment, I would rather': string;
  // 'Some teachers start their lessons with an outline of what they will cover. Such outlines are': string;
  // 'During online classes, some teachers would start their lessons with an outline of what they will cover. Such outlines were': string;
  // 'The idea of doing homework in groups, with one grade for the entire group,': string;
  // 'During online learning, the idea of doing homework in groups, with one grade for the entire group,': string;
  // 'When I do long calculations,': string;
  // 'While studying via online mode, when I did long calculations,': string;
  // 'I tend to picture places I have been to': string;
  // 'During lockdown, I tended to picture places I have been to': string;
  // 'When solving problems in a group, I would be more likely to': string;
  // 'In online mode, when solving problems in a group, I would be more likely to': string;
}
